/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class AESCMiddleware */

#ifndef _Included_AESCMiddleware
#define _Included_AESCMiddleware
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     AESCMiddleware
 * Method:    initFromC
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_AESCMiddleware_initFromC
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     AESCMiddleware
 * Method:    updateFromC
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_AESCMiddleware_updateFromC
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     AESCMiddleware
 * Method:    doFinalFromC
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_AESCMiddleware_doFinalFromC
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
